permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Danqi Zhu
  email: zhudanqi888@gmail.com
  link: http://zhu-dq.github.io
  weibo: http://weibo.com/2401226655
  github: http://github.com/zhu-dq

# 站点信息
title: 朱旦奇的博客
description: My personal blog
url: http://zhu-dq.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png


# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档